### ISSUE TITLE
Blacklist funktioniert nicht (für Sky Sender)

### ISSUE THREAD

**Issue by ppb1308** [iobroker-community-adapters/ioBroker.tvspielfilm#23]
Hallo,

kann es sein, dass die Blacklist nicht korrekt funktioniert?
Zumindest kann ich keine Sky Sender aus der Selektion ausschließen, habe die Whitelist leer und mittlerweile diesen Eintrag unter Blacklist:
SKY*, Sky*, sky*
In Spielfilme werden mir trotzdem z.B. Sky Family Einträge angezeigt.

Komma und Leerzeichen als Trenner ist ok, hab ich so in der Doku gesehen?

Woran könnte das liegen?
Adapter ist aktuell (2.0.1) alle anderen sind auch aktuell (latest Repo).

Gruß,
Peter

**Comment by Pix---** [comment]
Hallo Peter,

ich kann bisher keine Probleme feststellen.
Daher habe ich gerad zum Test deine Blacklist
`SKY*, Sky*, sky*`
in die Whitelist eingetragen und die Blacklist in der Konfiguration gelöscht. Ergebnis: es werden keine Sender angezeigt.
Dann allerdings sollten alle Sky-Sender angezeigt werden. Die Lösung: Es wird nur explizit der Sendername, der auch von tvspielfilm verwendet wird mit den beiden Listen abgeglichen. Etwas wie eine _Sky-Gruppe_ oder _ProSiebenSat.1_ oder _RTL Gruppe_ gibt es leider nicht. Wenn die Redaktion von tvspielfilm zum Beispiel `RTL Nitro` nur noch `NITRO` nennt, wird der Sender durch die Eingabe` RTL*` nicht gefunden.

Du musst also jeden einzelnen unerwünschten Sender in die Blacklist aufnehmen, wenn keine gemeinsamen Namensteile verwendet worden sind. Am besten per Copy&Paste, dann ist die Schreibweise garantiert korrekt.

Gruß
Pix

**Comment by ppb1308** [comment]
Hallo Pix,

danke für die Erklärung, das hatte ich so schon verstanden.

Ich habe nur die Blacklist gepflegt, aktuell wird dann aber trotzdem z.B. "Sky Action" und auch "Sky Cinema" in der "Spielfilme" Liste angezeigt; siehe Screenshot.
![ioBroker_TV-Spielfilm_Sky_Bug](https://user-images.githubusercontent.com/16593386/99827921-8c8c7b80-2b5a-11eb-9961-525284f2b851.png)

Also funktioniert das dafür zumindest für diese Spielfilm-Liste nicht. 
In der 20:15/22:00 Liste sind keine Sky Sender drin, da greift die Blacklist wohl korrekt.

Viele Grüße,
Peter
