### ISSUE TITLE
Langbeschreibung und Bilder ausblenden

### ISSUE THREAD

**Issue by Fritzelspitze** [iobroker-community-adapters/ioBroker.tvspielfilm#29]
Mich interessiert oft weder das Bild noch die Langbeschreibung. Daher würde ich diese am liebsten über die Konfiguration ausblenden und nur die Uhrzeit samt Sender und Sendungsname anzeigen lassen, dafür deutlich mehr Sender gleichzeitig sehen.

**Comment by Pix---** [comment]
Hallo @Fritzelspitze,

du kannst leicht über CSS die nicht gewünschten Elemente ausblenden. Die [CSS-Doku ](https://github.com/Pix---/ioBroker.tvspielfilm/blob/master/docs/de/doc_tvspielfilm_de.md#css-konfiguration) gibt hier einige Hinweise.

Für Deine gewünschte Ansicht ohne Bild empfehle ich, die erste Spalte ganz auszublenden:

`.tclass-th1 { /* linker Header */
    display: none;/* ganze Spalte ausblenden */
}`

Die Langbeschreibung ist die zweite Reihe in der Unter-Tabelle den zweiten, rechten Spalte. Kannst Du so ausblenden: 

`.tclass-th2 tbody tr:nth-child(2) {
    display: none;
}`

Wenn das nur für eine bestimmte Rubrik passieren soll (z.B. nur TV-Tipps), dann so:

`.tclass-th2 .tv_tipps tbody tr:nth-child(2) {
    display: none;
}`

Gruß
Pix
