### ISSUE TITLE
Objects are not written properly

### ISSUE THREAD

**Issue by pcjogi** [iobroker-community-adapters/ioBroker.tvspielfilm#33]
I have had installed the Version 2.04 which worked perfect. But sometime (I do not hafe a glue when and why) the objects where not written properly. 
Deleting the adapter an reinstalling does not change the behavior. 
After reinstalling the adapter only filled the heute2015 objects

iobroker is running in a docker container on a synology and everything is updated to the last version.

Any idea?

Thanks

**Comment by dft601** [comment]
I have the same issue, but from the beginning... only heute2015 is filled in json and raw.
Also after update 2.0.5
